/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VaultCard: typeof import('./../components/VaultCard/Index.vue')['default']
    VaultDialog: typeof import('./../components/VaultDialog/Index.vue')['default']
    VaultDrawer: typeof import('./../components/VaultDrawer/Index.vue')['default']
    VaultExcel: typeof import('./../components/VaultExcel/Index.vue')['default']
    VaultGlobalIcon: typeof import('./../components/VaultGlobalIcon/Index.vue')['default']
    VaultLoading: typeof import('./../components/VaultLoading/Index.vue')['default']
    VaultMobileDrawer: typeof import('./../components/VaultMobileDrawer/Index.vue')['default']
    VaultSearch: typeof import('./../components/VaultSearch/Index.vue')['default']
    VaultSelectIcon: typeof import('./../components/VaultSelectIcon/Index.vue')['default']
    VaultSvgIcon: typeof import('./../components/VaultSvgIcon/Index.vue')['default']
    VaultTag: typeof import('./../components/VaultTag/Index.vue')['default']
    VaultTagFilter: typeof import('./../components/VaultTagFilter/Index.vue')['default']
    VaultToolbar: typeof import('./../components/VaultToolbar/Index.vue')['default']
    VaultUploadFiles: typeof import('./../components/VaultUpload/Files.vue')['default']
    VaultUploadImage: typeof import('./../components/VaultUpload/Image.vue')['default']
    VaultUploadImages: typeof import('./../components/VaultUpload/Images.vue')['default']
  }
}
